# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('keddah2-example', ['keddah2'])
    obj.source = 'keddah2-example.cc'

